window.VIDEO_URLS = {
  "americone-dream": "https://www.instagram.com/p/DKDB8PYS3t7/?hl=en",
  "baked-alaska": "https://www.instagram.com/p/DNd6thUyo6U/",
  "brownie-batter-blizzard": "https://www.instagram.com/p/DRxn8POkvZh/",
  "cake-batter-cookie-dough-blizzard": "https://www.instagram.com/p/DLTCAnWS6K9/",
  "cherry-garcia": "https://www.instagram.com/p/DH9V5beSbsy/",
  "choco-brownie-extreme-blizzard": "https://www.instagram.com/p/DLlHa9wyEoR/",
  "choco-lotta-cheesecake-sundae": "https://www.instagram.com/p/DSIzLgLksBi/",
  "chocolate-caramel-cheesecake": "https://www.instagram.com/p/DOByjtLDmlN/",
  "chocolate-chip-cookie-dough": "https://www.instagram.com/p/DJpc6oJS0B8/",
  "chocolate-covered-strawberry": "https://www.instagram.com/p/DQPiUjzDroT/",
  "chocolate-fudge-brownie": "https://www.instagram.com/p/DImWyj2SWBa/",
  "chocolate-love-a-fair": "https://www.instagram.com/p/DQC9eNIjsEr/",
  "chocolate-therapy": "https://www.instagram.com/p/DNWTyXUyhar/",
  "chubby-hubby": "https://www.instagram.com/p/DKnQvCnyLdH/",
  "chunky-monkey": "https://www.instagram.com/p/DQ4-fw4Dr6y/",
  "churray-for-churros": "https://www.instagram.com/p/DMlcVVhSzFp/",
  "cinnamon-bun": "https://www.instagram.com/p/DKagUicyw_B/",
  "coffee-coffee-buzzbuzzbuzz": "https://www.instagram.com/p/DM6DDUcSjGc/",
  "coffee-toffee-bar-crunch": "https://www.instagram.com/p/DKfpXoKy8XA/",
  "confetti-cake-blizzard": "https://www.instagram.com/p/DK0MGBQyPsU/",
  "cookie-dough": "https://www.instagram.com/p/DKIZ7RdSz5-/",
  "cosmic-brownie": "https://www.instagram.com/p/DRLFzMujh2u/",
  "cotton-candy-blizzard": "https://www.instagram.com/p/DLGJM9RyEcB/",
  "death-by-chocolate": "https://www.instagram.com/p/DI68Y3rSSvq/",
  "dirt-cake": "https://www.instagram.com/p/DLfZVQ1sYPt/",
  "double-oreo": "https://www.instagram.com/p/DWHm8M_JxVN/",
  "everything-but-the": "https://www.instagram.com/reel/DPPT2nojowx/",
  "frosted-animal-cookie-blizzard": "https://www.instagram.com/p/DPE-FncjtJG/",
  "frosted-sugar-cookie-blizzard": "https://www.instagram.com/p/DRAs16pDk8C/",
  "gimme-smores": "https://www.instagram.com/p/DMLrsLXSYOp/",
  "glampfire-trail-mix": "https://www.instagram.com/reels/DVmA1sBjowk/",
  "gooey-butter-cake": "https://www.instagram.com/p/DVzAi-YDmgD/",
  "half-baked": "https://www.instagram.com/p/DK7tiTWyoHy/",
  "half-baked-twist": "https://www.instagram.com/p/DWhW6A0JTzR/",
  "impretzively-fudged": "https://www.instagram.com/p/DOWq1jREW-G/",
  "jamoca-almond-fudge": "https://www.instagram.com/p/DT3hWJdjp7Q/",
  "key-lime-pie": "https://www.instagram.com/p/DUbm_RckjB4/",
  "lights-caramel-action": "https://www.instagram.com/p/DKN6eBdsOef/",
  "mandm-mcflurry": "https://www.instagram.com/p/DDOKQ4UPo7a/",
  "marshmallow-sky": "https://www.instagram.com/p/DL3GUT_yYdp/",
  "milk-and-cookies": "https://www.instagram.com/p/DLA_TiCSl9R/",
  "minter-wonderland": "https://www.instagram.com/p/DS5uQbzjlev/",
  "netflix-and-chilld": "https://www.instagram.com/p/DT_O-TKDju0/",
  "new-york-super-fudge-chunk": "https://www.instagram.com/p/DMV7A5WyVUX/",
  "nutella": "https://www.instagram.com/p/DGq7V0AS_Y6/",
  "oat-of-this-swirled": "https://www.instagram.com/p/DLLVjnOMOFC/",
  "one-love": "https://www.instagram.com/p/DOjIp8vDp3B/",
  "oreo-mcflurry": "https://www.instagram.com/p/DRnUy1dDnvC/",
  "pb-over-the-top": "https://www.instagram.com/p/DU_nhHZjc11/",
  "peanut-butter-cup": "https://www.instagram.com/p/DNoTWbaOBI_/",
  "peanut-butter-half-baked": "https://www.instagram.com/p/DP1_Yh6jgvo/",
  "peanut-butter-world": "https://www.instagram.com/p/DMQx6aqSUkG/",
  "phish-food": "https://www.instagram.com/p/DToKDGbDmq_/",
  "pistachio-pistachio": "https://www.instagram.com/p/DPmiPjyjg4J/",
  "pumpkin-cheesecake": "https://www.instagram.com/p/DO6vAy5DtCr/",
  "pumpkin-pie-blizzard": "https://www.instagram.com/p/DOeYJyzjuwd/?hl=en",
  "raspberry-cheesecake-topped": "https://www.instagram.com/p/DUrBMTpCYMl/?hl=en",
  "red-velvet-cake-blizzard": "https://www.instagram.com/p/DUwKzKfEbJ4/?hl=en",
  "red-velvet-cake": "https://www.instagram.com/p/DSx_1srjqah/",
  "red-velvet": "https://www.instagram.com/p/DGByFDGxP0T/",
  "reeses-caramel-craze-blizzard": "https://www.instagram.com/p/DNjJqg4SeGW/",
  "rocky-road": "https://www.instagram.com/p/DUT4j7CkqRD/",
  "royal-new-york-cheesecake-blizzard": "https://www.instagram.com/p/DMvtcn6ySqJ/",
  "royal-reeses-fluffernutter-blizzard": "https://www.instagram.com/p/DNOsq4-ypCN/",
  "salted-peanut-butter-with-chocolate-flecks": "https://www.instagram.com/p/DVehETYFL9q/",
  "salty-caramel": "https://www.instagram.com/reels/DWcNRI_J1F_/",
  "shamrock-oreo-mcflurry": "https://www.instagram.com/p/DVPEW9LCYhI/",
  "shamrock-shake": "https://www.instagram.com/p/DHJxJ2nyfmJ/",
  "smores-blizzard": "https://www.instagram.com/p/DMD85J6yYrM/",
  "snowdrift-blizzard": "https://www.instagram.com/p/DSlS7TMDlvK/",
  "strawberry-cheesecake": "https://www.instagram.com/p/DQaAz0VkvMj/",
  "tart-frozen-yogurt": "https://www.instagram.com/p/DEliAsZvqt-/",
  "the-tonight-dough": "https://www.instagram.com/p/DQphqpVEvSE/",
  "tiramisu-topped": "https://www.instagram.com/p/DPcEuIQDjC8/",
  "turtle-pecan-cluster": "https://www.instagram.com/p/DJht0r1ydg1/",
  "vanilla-pecan-blondie": "https://www.instagram.com/p/DLYRV2XyZ0P/"
};

// Applique les liens vidéo aux recettes avant le chargement de app.js.
if (window.RECIPES && window.VIDEO_URLS) {
  window.RECIPES.forEach(recipe => {
    const url = window.VIDEO_URLS[recipe.id];
    if (url) recipe.videoUrl = url;
  });
}
